--!strict
-- I HAD to make this module because of how poor luau lsp works ;-;

export type FrameObject = Frame
export type CanvasGroupObject = CanvasGroup
export type ImageLabelObject = ImageLabel
export type ImageButtonObject = ImageButton
export type TextButtonObject = TextButton
export type TextLabelObject = TextLabel
export type TextBoxObject = TextBox
export type ScrollingFrameObject = ScrollingFrame
export type ViewportFrameObject = ViewportFrame
export type VideoFrameObject = VideoFrame

return {}