-- Just a readme file basically heh

--[[
PeanutUI by koeqaife (hi)
    (Definitely not a random name I made when I was eating PEANUTS)

Helllooo there! I created this mainly for myself, but it turned out so cool that I wanted to share it!
It's heavily inspired by vue.js because I was coding on it a lot and loved how it works.

I spent a lot of time making this framework, it was really hard to find out how to properly do stuff.
Like, modifiers is completely my idea, and I love how I made it, it looks and works just perfectly!
    (except it breaking luau lsp that I had to make bug report T_T)

I hope you will love using this framework!!! As it's made with some love and understanding hehe...
And it fixes soo many things you would have with other frameworks or if you code your own libraries.
    (who even does that??? Definitely not me... Right? Right???....)

This message was written on 2026-09-05 04:16am, yeah yeah I'm not sleeping...
]]
